#!/bin/bash
# Auto-generated from .env - DO NOT EDIT
export VITE_PORT="1420"
export PHP_SERVER_PORT="8088"
export VITE_PHP_SERVER_PORT="8088"
export VITE_FILE_PHP="assets/svg/todo.php.svg"
export WINDOW_WIDTH="1050"
export WINDOW_HEIGHT="780"
export SVG_WIDTH="1000"
export SVG_HEIGHT="700"
export VITE_DEV_URL="http://localhost:${VITE_PORT}"
export PHP_SERVER_URL="http://localhost:${PHP_SERVER_PORT}"
export PDF_PROCESSOR_URL="http://localhost:${PHP_SERVER_PORT}/${VITE_FILE_PHP}"
export ENABLE_VERBOSE_LOGGING="false"
export LOG_DIRECTORY="logs"
export NODE_ENV="development"
